baseURL: https://dasfranck.fr
title: Vimarkish
theme: eleganthugo

languageCode: fr-fr
DefaultContentLanguage: fr

pygmentsCodeFences: true
pygmentsUseClasses: true

enableRobotsTXT: true

Author:
  github: DasFranck
  linkedin: franck-hochstaetter-b710b910a
  name: '"Das" Franck Hochstaetter'
  reddit: DasFranck
  stackoverflow: users/4836782/dasfranck
  website: https://dasfranck.fr

Params:
  dateFormat: 2 January 2006 15:04
  favicon: images/icons/favicon.png
  logo: images/icons/avatar-icon.png
  readingTime: true
  rss: true
  socialShare: true
  subtitle: Un blog de ouiche et de DevOps

menu:
  main:
  - name: Posts
    url: posts/
    weight: 1
  - name: À propos
    url: pages/about/
    weight: 2
  - name: Tags
    url: tags
    weight: 3